[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.4", "conan>=2.0", "cmake>=3.26"]
build-backend = "setuptools.build_meta"

[tool.black]
exclude = '.+\.pyi'  # exclude type stubs from formatting